### ISSUE TITLE
Увеличение продолжительности жизни ссылки для оплаты

### ISSUE THREAD

**Issue by deesiigneer** [sp-worlds/api-docs#13]
# Увеличение продолжительности жизни ссылки для оплаты
В #9 сказано, что ссылка действительна 5 минут, этого иногда бывает очень мало, человек отвлекается больше чем на 5 минут и ссылка уже не активна. Можно пересоздать ссылку с новым `data` внутри (вроде должно помочь), но не всегда есть возможность пересоздать, да и уследить за этим не всегда получится.

Предлагаю сделать:
 - дать возможность указывать продолжительность жизни ссылки в [payments](https://github.com/sp-worlds/api-docs/blob/main/PAYMENTS.md)
- или увеличить до 24 часов

**Comment by N3wSk1Y** [comment]
Поддерживаю

**Comment by TheHardNar** [comment]
реально кста

**Comment by Karonus** [comment]
Срок действия ссылки увеличен до 24 часов
