### ISSUE TITLE
Hash тела запроса

### ISSUE THREAD

**Issue by mrloller** [sp-worlds/api-docs#14]
Я не понял как работает система подтверждения запроса с вашего сайта при оплате АРами. Если я правильно понял, то мне нужно взять JSON из тела запроса, затем создать его хэш, использовав как ключ токен карты, затем закодировать в base64 и сравнить с хедером x-body-hash. Однако в самом хедере содержится какая-то непонятная сама по себе строка, которая при декодировании выдаёт непонятный результат, явно не совпадающий с хешем. Что я делаю не так?

**Comment by deesiigneer** [comment]
> Для этого в хедерах запроса есть хедер `X-Body-Hash` который содержит закодированный в base64 SHA256 [HMAC](https://ru.wikipedia.org/wiki/HMAC) хеш тела запроса, использующий как ключ api токен вашей карты. При приеме запроса вы сначала должны сгенерировать свой хеш и убедиться что он совпадает с хедером, прежде чем обрабатывать запрос.

С помощью HMAC нужно закодировать токен и тело запроса в SHA256, которую затем всё в base64 и опять же с помощью HMAC сравнить подлинность того что вышло с `X-Body-Hash` хедером.

Было бы круто увидеть код, может дело в нём.

В доке всё нормально написано и тем более всегда можно посмотреть код [библиотек](https://github.com/sp-worlds/api-docs#%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-api) или посмотреть пример с моей [python библиотеки](https://github.com/deesiigneer/pyspapi/blob/0667922c8c1abff8c1054a8a66e3595314f34ace/spapi/__init__.py#L59)

**Comment by mrloller** [comment]
Ура, я разобрался с проблемой. Оказывается hash был бинарным, а php по дефолту делает его нормальным, если не указывать специальный параметр. Но так как о нём нигде не было написано, мне даже в голову не пришло его поставить. @ronanru просьба написать, что Хэш бинарный, чтобы в будущем у таких людей как я не возникало проблем.
