### ISSUE TITLE
Сервер не отправляет POST запросы webhookUrl

### ISSUE THREAD

**Issue by N3wSk1Y** [sp-worlds/api-docs#15]
При оплате через SPworlds, сервер не отправляет POST запрос на ссылку, указанную в `webhookUrl`
<img src="https://i.imgur.com/LcTrstW.png">

**Comment by deesiigneer** [comment]
было, проходили.

Почему-то не отправляет на ip:port, попробуй сначала прямо на ip если нет, тогда придется домен прикручивать и только так.

**Comment by N3wSk1Y** [comment]
Спасибо, уже пофиксил. Прилепил домент и SSL сертификат.
