### ISSUE TITLE
Добавление дополнительной python библиотеки

### ISSUE THREAD

**Issue by teleport2** [sp-worlds/api-docs#16]
Здравствуйте, предлагаю добавление Py-SPW как python библиотеку для SPworlds API
[PyPi](https://pypi.org/project/Py-SPW/), [GitHub](https://github.com/teleport2/Py-SPW), [Docs](https://github.com/teleport2/Py-SPW/wiki)
Преимущество над pyspapi:
- Более структурированная документация
- Дополнительные функции, такие как: 
  - создание сразу нескольких платежей, вызовом одного метода.
  - отправка сразу нескольких транзакций, вызовом одного метода. 
  - Получение статуса проходки как boolean
  - Получение изображение скина или его части (примеры можно посмотреть [здесь](https://visage.surgeplay.com/index.html))
  - Получение ссылки на изображение скина или его части
- Не нужно парсить Json или брать значения из Dict

**Comment by teleportx** [comment]
Обновил библиотеку. Добавлена возможность получить историю никнеймов. В лучшую сторону изменены некоторые функции. Также немного изменена документация для более удобного пользования. Прошу Ронана все же не игнорить и сделать  Py-SPW как вторую библиотеку, хотя-бы для того что-бы у людей была альтернатива. Или не слелать и закрыть issue
