### ISSUE TITLE
Отправляет Access denied и вместо json ответа получаю html 1020 ошибка

### ISSUE THREAD

**Issue by ValeraShimchuck** [sp-worlds/api-docs#19]
![image](https://user-images.githubusercontent.com/32999269/180277656-7599e5ba-18c6-4552-9b8a-d9e426c30e7b.png)
ray id 72e5a811be61b324
ошибка 1020.
Попытался получить баланс карты, но в итоге мне кинуло это. Данные карты могли быть не валидны, поскольку я не знаю валидны они или нет.

**Comment by deesiigneer** [comment]
Сайт дудосят, по этому клаудфаер видимо шлёт всех)

**Comment by teleport2** [comment]
дудосеры сосатб

**Comment by ronanru** [comment]
Сайт дудосили и временно отключили доступ. Если все еще нет доступа, то значит это ты сайт дудосил и тебя забанили за дудос.

**Comment by ValeraShimchuck** [comment]
Да, дудосил(рофлян), отправил 1 запрос, естественно я НЕ МОГ подтвердить что я не робот, потому что ЭТО API. У вас система кривая, отправил 1 запрос в API, естественно ЭТО НЕЛЬЗЯ ПОДТВЕРДИТЬ и сразу бан и все соси жопу, очень логично сделано, ну что за тупость и что за ответы на отьебись? До сих пор я не могу зайти, могу в личку ip покидать и по ЛОГАМИ посмотрите, что я максимум 2-3 запроса кинул, потому что все легло и мне нужно было бота чинить.

**Comment by N3wSk1Y** [comment]
> Сайт дудосили и временно отключили доступ. Если все еще нет доступа, то значит это ты сайт дудосил и тебя забанили за дудос.

API постоянно отправляет запросы для проверки пользователя, его забанило. Через сколько автоматически приходит разбан?

**Comment by ronanru** [comment]
Никогда. Поменяй айпи.

**Comment by ValeraShimchuck** [comment]
Уже разбанило, но дичь с бот проверкой на апи это немного бред.

**Comment by ronanru** [comment]
> Уже разбанило, но дичь с бот проверкой на апи это немного бред.

Согласен, но так Cloudflare работает, мы это не можем поменять. Тем более DDoS атаки достаточно редко происходят.
