### ISSUE TITLE
Добавление библиотеки pyspapi

### ISSUE THREAD

**Issue by deesiigneer** [sp-worlds/api-docs#2]
## Ссылки
[pyspapi github](https://github.com/deesiigneer/pyspapi)

[pyspapi pypi](https://pypi.org/project/pyspapi/)

**Comment by ronanru** [comment]
Можешь добавить метод для проверки хеша в вебхуке? Я не хочу добавлять неполную библиотеку.

**Comment by deesiigneer** [comment]
> Можешь добавить метод для проверки хеша в вебхуке? Я не хочу добавлять неполную библиотеку.

Я без проблем могу добавить, но с тестированием проблемы... У меня проходка только на СПк, я не могу нормально протестировать оплату(. 

И было бы круто отправлять запрос, с проверкой оплатил или нет, альтернативно вебхуку.

**Comment by deesiigneer** [comment]
@ronanru сделано.
