### ISSUE TITLE
Автоблокировка API

### ISSUE THREAD

**Issue by N3wSk1Y** [sp-worlds/api-docs#21]
Можете, пожалуйста, убрать блокировку запросов к API, очень сильно мешает, бот постоянно проверяет пользователей, много запросов.

**Comment by ronanru** [comment]
API предоставляется и хостится абсолютно бесплатно для любого игрока сервера. У нас вполне нормальный лимит, такой же как и у большинства других API сервисов. Когда ты делаешь много запросов, это сильно нагружает сервер и портит experience другим игрокам. Прости, но нет, Won't fix.
