### ISSUE TITLE
POST https://spworlds.ru/api/public/users/

### ISSUE THREAD

**Issue by deesiigneer** [sp-worlds/api-docs#22]
Сейчас что бы получить пользователя с API, приходится каждый раз делать новый запрос и если это *список* и их там около 100, то придется долбиться к APIшке 100 раз, что бы получить каждого из списка.

Предлагаю:
Добавить новый запрос `POST https://spworlds.ru/api/public/users/` в [Получение ника](https://github.com/sp-worlds/api-docs/blob/main/USERS.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-discord-id) и добавить body, где будет список `DISCORDID`, это надеюсь разгрузит APIшку и людям не придется делать 100 запросов в секунду на 100 людей из списка.

[пример из Mojang API](https://wiki.vg/Mojang_API)
![image](https://user-images.githubusercontent.com/22377585/180496556-50e25b23-fa8f-4676-835b-f958fb470e45.png)

**Comment by N3wSk1Y** [comment]
Проще просто убрать защиту от DDoS для API, ибо доступ к нему имеют только игроки СП, а вряд ли кто-то будет рисковать своим аккаунтом ради этого.

**Comment by deesiigneer** [comment]
> Проще просто убрать защиту от DDoS для API, ибо доступ к нему имеют только игроки СП, а вряд ли кто-то будет рисковать своим аккаунтом ради этого.

Я не говорю про защиту от DDoS, я предлагаю разгрузить API.

Повторюсь, лучше сделать 1 `POST` запрос чем 100 `GET`

**Comment by teleport2** [comment]
Эта такое надо

**Comment by ronanru** [comment]
Спасибо за сообщение. Этот эндпоинт предназначен для реализации входа на сайт или в дискорд. Поэтому такая фича не входит в наши планы для api.
