### ISSUE TITLE
Неверный код HTTP 

### ISSUE THREAD

**Issue by teleport2** [sp-worlds/api-docs#24]
При попытке открыть несуществующее дело в суд с буквеным адресом (пример https://spworlds.ru/sp/lawsuits/Любые-символы).
Выдает ошибку 500, что означает ошибку на сервере. **Должно по идеи выдавать ошибку 404.**
![изображение](https://user-images.githubusercontent.com/77507478/181299516-cafd92f3-0d82-4a54-8ccf-9ec6640cd736.png)

В случае если попробовыть перейти по несуществующему делу в суд с числовым идентификатором (пример https://spworlds.ru/sp/lawsuits/14134) выдает ошибку 404 
![изображение](https://user-images.githubusercontent.com/77507478/181300882-bba488a0-8b00-4eb5-b68e-739b895ba153.png)

**Comment by ronanru** [comment]
Закрываю потому что не связано с api.
Спасибо за сообщение, обязательно пофиксим.

**Comment by teleport2** [comment]
Так это апи, только закрытое
