### ISSUE TITLE
В переводах нет ограничения на параметр comment

### ISSUE THREAD

**Issue by mhamsterr** [sp-worlds/api-docs#25]
В api отсутствует ограничение на кол-во символов в параметре `comment` в функции [переводов на карту](https://github.com/sp-worlds/api-docs/blob/main/CARD.md#как-переводить-деньги-с-карты-при-помощи-api), из-за чего во вкладке "Кошелёк" могут возникнуть довольно интересные ситуации с наложением текста комментария на дату и время
![Снимок экрана 2022-09-06 в 13 25 58](https://user-images.githubusercontent.com/81412348/188562259-b094448d-e507-4f16-9c08-3a8f6f7a912c.png)

При попытке сделать перевод на сайте с превышением лимита в 32 символа, он справедливо выдаст ошибку (правда на английском почему-то)

![Снимок экрана 2022-09-06 в 13 06 12](https://user-images.githubusercontent.com/81412348/188559758-e3235aec-d9b7-4dc7-b2b4-48edf5adeb58.png)

**Comment by ronanru** [comment]
Прикольдас. Спасибо за репорт, обязательно поправим!
