### ISSUE TITLE
Невозможно получить токен карты на СПб

### ISSUE THREAD

**Issue by Syjalo** [sp-worlds/api-docs#28]
Alert получения токена карты на СПб говорит, что токен будет отправлен через Minecraft на сервер, но на какой? На СПб и СПв ничего не приходит. Полагаю токен отправляется на СП, но доступа к нему нет.

**Comment by ronanru** [comment]
токен отпраляется на СПб

**Comment by Syjalo** [comment]
Сколько бы не пытался, даже с телефона, не получается.

<details>

![image](https://user-images.githubusercontent.com/62868468/192902254-3b986d5e-d93e-4426-b09c-26a45c51176b.png)

</details>

**Comment by YaFlay** [comment]
У меня точно так же, ни в дс спв, ни в дс спб, ни на спв, ни на спб, нигде не приходит

**Comment by yawaflua** [comment]
@Karonus закрывай issue, уже можно получать токен на сепебе сразу после перезагрузки сервера
