### ISSUE TITLE
Альтернативные способы получения информации о платежах

### ISSUE THREAD

**Issue by Syjalo** [sp-worlds/api-docs#29]
В данный момент для получение результата платежа происходится запрос сервера SPWorlds к Webhook, указанный в платёжной форме. Это не удобно для приложений, которые взаимодействуют с пользователем не через собственный сайт, например, Discord бот. Хотелось бы иметь возможность получать данные другими способами, например, через WebSocket или Long Polling.
Также раз у приложения нет собственного сайта, то хотелось бы увидеть стандартные страницы успешной или неудачной оплаты, которые будут показаны пользователю в зависимости от ответа приложения.

**Comment by ronanru** [comment]
Вебсокеты и Long Polling невозможно реализовать технически из-за того как устроена наша анти-дудос защита. Также эти технологии требуют 24/7 соединения с нашим серверам, что будет значительно нагружать его. Простой веб сервер можно добавить в дискорд бота за 30 минут. Бесплатно можно получить и домен, и Динамический DNS, и SSL сертификат.

Мы бы хотели чтобы страницы успешной оплаты были персонализированы. Можно легко сделать сайт на любой no code платформе с текстом "Спасибо за оплату".
