### ISSUE TITLE
hash validation

### ISSUE THREAD

**Issue by alozoBack** [sp-worlds/api-docs#31]
есть уже тема с хешэм но понятней не становится, как он генерируется не понимаю пытался много раз сгенерировать и он не сходился. Я как понмаю ключ это api токен id:token в base64, а вот тело это {"data": "pon"} вроде пост запроса api а не вебхука, не шифрованая и потом все это в sha -> base64? если есть решение этого вопроса без апи библиотек на java буду рад разобрать сам код.

**Comment by deesiigneer** [comment]
> есть уже тема с хешэм но понятней не становится, как он генерируется не понимаю пытался много раз сгенерировать и он не сходился. Я как понмаю ключ это api токен id:token в base64, а вот тело это {"data": "pon"} вроде не шифрованая и потом все это в sha -> base64? если есть решение этого вопроса без апи библиотек на java буду рад разобрать сам код.

Там немного запутано расписано, но если не торопиться и внимательно вчитаться в текст [вот тут](https://github.com/sp-worlds/api-docs/blob/main/PAYMENTS.md#L36), то во первых сразу станет понятно, что `id`, никак не используется, только токен. Далее token + data, оборачиваем в sha256 HMAC и после в  base64. И все, можно смело сравнивать с тем, что возвращает апишка spworlds в хедере.
Не особо шарю за Java, но лично у меня в pyspapi работает так.

Кстати, там частенько апишка отваливается, мониторить ее статус можно [тут](https://uptime.deesiigneer.ru/status/spworlds) (ловко это я рекламу своего сервиса подкинул, а?)

**Comment by deesiigneer** [comment]
> Я вот проснулся час назад собрался с мыслями и понял что не понял дата это request `{"amount": "1","redirectUrl": "https://peepo.ru","webhookUrl": "https://example/response","data": "test"}` или ответ на вебхук `{"data":"test","amount":1,"payer":"ALoZoOff"}` и в json'e оборачивать c токеном?
> 
> Ловко подкинул реально, а есть какой-то апи на сервисе я бы в мод прикрутил чтобы смотреть статус.

`data` - это то, что отправил сайт spworlds на твой `webhookUrl`. [Вот](https://github.com/deesiigneer/pyspapi/blob/eff14052fdc620221400f554278f074af78ef069/pyspapi/api.py#L127), можешь посмотреть пример только он на питоне. 

`token` + `data`, шифруем это всё в sha256 HMAC и после, то что вышло в base64. Сравниваешь, то что вышло у тебя и то что отправил spworlds в header `X-Body-Hash`. 

API у [сервиса ](https://uptime.deesiigneer.ru/status/spworlds)к сожалению нету)
