### ISSUE TITLE
Загрузочный экран при curl запросе

### ISSUE THREAD

**Issue by zaralX** [sp-worlds/api-docs#35]
``Иногда когда я делаю запрос в итоге получается Null тк при json_decode он пытается обработать загрузочный экран api???
Почините пожалуйста, или скажите как это фиксить

php код:
```php
$url = "https://spworlds.ru/api/public/users/".$discord_id;

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, false);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

curl_setopt($curl, CURLOPT_HTTPHEADER, array(
    "Accept: application/json",
    "Content-Type: application/json",
    "Authorization: Bearer TOKEN"
));

$resp = curl_exec($curl);
curl_close($curl);
```

```echo $resp;```
![image](https://github.com/sp-worlds/api-docs/assets/61970128/95e6df3f-6758-4120-85b3-690573357ada)

```echo json_decode($resp);```
> NULL

**Comment by zaralX** [comment]
![image](https://github.com/sp-worlds/api-docs/assets/61970128/dd145ddc-9e1f-461e-8491-0d1494d94fa9)
Даже на сторонних сайтах с запросами тоже самое

**Comment by zaralX** [comment]
https://github.com/sp-worlds/api-docs/assets/61970128/1baba3f9-6f2b-4086-9fc1-4aa8869eb6f2

Даже так..

**Comment by zaralX** [comment]
**Догадка** 
В Headers экрана загрузки находятся данные cloudflare
Вероятно он включает защиту когда на сайте большой трафик и при этом эта защита начинает действовать и на API

Что с этим делать мне я без понятия, а начёт разработчика.. прошу отключить загрузочный экран на api страницы

**Comment by deesiigneer** [comment]
Сделай проверку, если бублик(cloudflare включил защиту) есть, то повтори запрос через 1 минуту. По статистике с [моего uptime](https://uptime.deesiigneer.ru), проблемы проходят в среднем после 1-5 минут.

**Comment by zaralX** [comment]
> Сделай проверку, если бублик(cloudflare включил защиту) есть, то повтори запрос через 1 минуту. По статистике с [моего uptime](https://uptime.deesiigneer.ru), проблемы проходят в среднем после 1-5 минут.

Хорошо.

**Comment by Karonus** [comment]
Это связано с работой защиты от ботов. Если данная проблема сохранится, но вам нужен доступ к API, обратитесь к нам на почту help@spworlds.ru. В своем обращении укажите следующую информацию:
1. Ваша проблема.
2. Для чего вам нужен доступ к API.
3. IP адрес, с которого будут отправляться запросы к API (он должен быть статическим).

**Comment by zaralX** [comment]
> Это связано с работой защиты от ботов. Если данная проблема сохранится, но вам нужен доступ к API, обратитесь к нам на почту help@spworlds.ru. В своем обращении укажите следующую информацию:
> 1. Ваша проблема.
> 2. Для чего вам нужен доступ к API.
> 3. IP адрес, с которого будут отправляться запросы к API (он должен быть статическим).

Да вот они добавили но проблема не пропала..

**Comment by ostermine** [comment]
@zaralX напиши мне в тг я проверю точно ли твой айпи в вайт листе, а ты убедись то что ты с того же айпи шлёшь запросы, если что потом могу задать вопрос в stormwall
