### ISSUE TITLE
Библиотека на GOLang

### ISSUE THREAD

**Issue by AndreyFulov** [sp-worlds/api-docs#36]
https://github.com/AndreyFulov/spworlds

**Comment by teleportx** [comment]
а где метод получения ника по discord id?

**Comment by AndreyFulov** [comment]
Будет добавлена со временем

**Comment by teleportx** [comment]
Я думаю стоит добавить сейчас, уже был такой прецедент https://github.com/sp-worlds/api-docs/issues/2#issuecomment-1147808386

**Comment by AndreyFulov** [comment]
Всё, сделал работу с Дискордом

**Comment by Karonus** [comment]
Библиотека использует старую версию API. Пожалуйста, ознакомьтесь с [новой документацией](https://github.com/sp-worlds/api-docs/wiki)
