### ISSUE TITLE
Возможно ли как-то хендлить все движения аров на счету?

### ISSUE THREAD

**Issue by yawaflua** [sp-worlds/api-docs#38]
Условно говоря, я отправляю на сервер PUT запрос для создания вебхука на ВСЕ оплаты, и при перечислении мне средств (без ссылок и т.д., просто с сайта) приходит вебхук об оплате, а я там его валидирую и т.д.

Существует ли это сейчас, и, если нет, то возможно ли это реализовать?

**Comment by YaFlay** [comment]
> https://github.com/sp-worlds/api-docs/blob/main/PAYMENTS.md

вчитайся что я написал, без ссылок и т.д. просто с сайта

**Comment by deesiigneer** [comment]
Если этого нету в доках, значит этого нет)
Я правда не особо все равно понял что ты хочешь. 
Просто скормить ссылку на свой сервер серверу сп, и он туда отправлял сообщения вместо того что бы пингать каждый раз? Если это так, то это крутая идея и я ее давно поддерживаю. Имхо это уменьшит кол-во запросов к серверу и спадет нагрузка на сервер. (Серверу что так, что так обработать запрос)

**Comment by YaFlay** [comment]
> Если этого нету в доках, значит этого нет) Я правда не особо все равно понял что ты хочешь. Просто скормить ссылку на свой сервер серверу сп, и он туда отправлял сообщения вместо того что бы пингать каждый раз? Если это так, то это крутая идея и я ее давно поддерживаю. Имхо это уменьшит кол-во запросов к серверу и спадет нагрузка на сервер. (Серверу что так, что так обработать запрос)

да, именно это я и хочу узнать, другой вариант это проверять каждые 10 секунд баланс на карте  последними транзакциями(не через оф. способы API, а напрямую, как это делает сайт), но из-за этого сервер взорвётся

**Comment by CheppyJam** [comment]
Сейчас подобные штуки прилетают в телегу.

Можешь костыльно так парсить. Официально мы врядли сделаем

**Comment by YaFlay** [comment]
> Сейчас подобные штуки прилетают в телегу.
> 
> Можешь костыльно так парсить. Официально мы врядли сделаем

Куда они прилетают?
Никто ни о чем не говорил, о пересылках вебхуков в тг, на сайте даже привязки тг нет. Ты о чем, брух?

**Comment by YaFlay** [comment]
Правда, это не работает, хд
Я потестил, оказалось, что подобные штуки в тг не приходят, так что какой-то банчик

![image](https://github.com/sp-worlds/api-docs/assets/93622229/f373fd3e-4f6d-4341-b116-7e1dfa49c297)
![image](https://github.com/sp-worlds/api-docs/assets/93622229/96304312-c35f-424f-844a-7e05e9acd605)

**Comment by CheppyJam** [comment]
В настройках нужно включить эти уведомления

**Comment by CheppyJam** [comment]
Именно на сайте

**Comment by YaFlay** [comment]
> В настройках нужно включить эти уведомления

Как-то неинтуитивно...
Да и к тому же, раз вы сделали такое уже сейчас, в чем проблема отправлять уведы на uri, с настройкой через майн/сайт/по токену(как я писал выше, отправлять запрос на условный "api/public/create_webhook")

**Comment by Karonus** [comment]
В обновленной APIшке добавлена возможность [установки вебхука](https://github.com/sp-worlds/api-docs/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B2%D0%B5%D0%B1%D1%85%D1%83%D0%BA%D0%B0).

**Следите за [новостями](https://t.me/spwdev), мы уведомим вас о переходе на новую версию API за неделю.**
