### ISSUE TITLE
SP API для C#

### ISSUE THREAD

**Issue by KOTOKOPOLb** [sp-worlds/api-docs#39]
SP API для C# https://github.com/KOTOKOPOlb/SP-Tools

**Comment by Karonus** [comment]
Хотелось бы увидеть возможность проверки хеша с вебхука, после успешной оплаты на сайте.
См. [клик](https://github.com/sp-worlds/api-docs/wiki/Оплата-на-вашем-сайте#получение-данных-об-успешной-оплате)

**Comment by KOTOKOPOLb** [comment]
Пока в процессе
