### ISSUE TITLE
Сделать гигачад юзера из стандартного юзера, возвращаемого с сайта, а еще сваггер в догонку

### ISSUE THREAD

**Issue by yawaflua** [sp-worlds/api-docs#40]
Ну реально, я не хочу ебаться с токенами авторизации, отправкой запросов на сайт ручками, чтоб походило на действия пользователя, а потом кидать запрос с ником(через костыли), чтоб получать номер карты блять.
Дайте мне пожалуйста такого гигачад-юзера(скрыл некоторые данные, чтоб сложнее было докопаться кто тут нахуй такой гений, не баньте на сайтике пж) для нормальной работы, а не обрубка, который дается сейчас
Вот собсна пример такого гигачад юзера:
```json
{
    "id": "",
    "isBanned": false,
    "user": {
        "isAdmin": false,
        "minecraftUUID": "",
        "username": "lan"
    },
    "roles": [],
    "city": {
        "mayor": {
            "id": ""
        },
        "name": "лады",
        "x": ,
        "z": 
    },
    "status": "",
    "createdAt": "2024-04-14T21:04:4.749Z",
    "cardsOwned": [
        {
            "name": "Шо ты палишь",
            "color": 5,
            "number": "пуки-каки",
            "id": ""
        }
    ],
    "isFollowed": false,
    "isFollowingYou": false
}
```

**Comment by yawaflua** [comment]
сваггер тоже полезная вещь для апишечки, пример вот: https://api.storespw.ru/
реально не понимаю почему нельзя его добавить, читать доки сайта в гите сложнее чем в сваггере

**Comment by deesiigneer** [comment]
У открытого api SPWorlds не больше 10 методов, для чего сваггер?

Гигачад юзер слишком уж у тебя гигачад, достаточно discord id, minecraft uid, nickname, может еще banned, что бы дурачков сразу отсеивать. А остальное зачем? Для чего??

**Comment by yawaflua** [comment]
> У открытого api SPWorlds не больше 10 методов, для чего сваггер?
> 
> Гигачад юзер слишком уж у тебя гигачад, достаточно discord id, minecraft uid, nickname, может еще banned, что бы дурачков сразу отсеивать. А остальное зачем? Для чего??

1) для удобства мейби? Тебе как котенку тыкаться в readme файлу будет удобнее, нежели в сваггере, где будут сразу и примеры, и то, что будет возвращаться, допустим, для удобного парсинга
2) для разных структур, это прям мега удобно, иметь номера карт сотрудников, которые получаются автоматом с сайта, для автоматического получения данных о том, где живет клиентик, так можно допустим(на примере маркета) указывать город с надписью: "вы хотите доставку сюда?", оплата на карту сразу продавцу, без дополнительных телодвижений

**Comment by yawaflua** [comment]
![image](https://github.com/sp-worlds/api-docs/assets/93622229/2f339c38-1e86-46b3-b2f3-4775d44e6aa1)
допустим, вот пример как работает моя команда для выдачи зпшек, он логинится(до этого конечно же, это же цикл), отправляет запрос на спворлдс, парсит эти данные, получает карту, а только после этого выдает

Очевидно же, что удобнее отправить запрос сразу по токену и карте, которые тебе дали в майне, нежели дрочить на айпишник, иначе спв отзывает токен, тогда надо получать новый ну и т.д.

**Comment by deesiigneer** [comment]
> 1) для удобства мейби? Тебе как котенку тыкаться в readme файлу будет удобнее, нежели в сваггере, где будут сразу и примеры, и то, что будет возвращаться, допустим, для удобного парсинга?


Повторю, в публичном апи пока не так много методов, что бы засовывать его в сваггер.

Насчет выдачи зп.
Почему бы не запросить у пользователя номер карты, записать в бд и вместо того, что бы досить парсером сайт спворлдс лишними запросами, вытаскивать необходимые данные из своей бд?

**Comment by yawaflua** [comment]
> > 1) для удобства мейби? Тебе как котенку тыкаться в readme файлу будет удобнее, нежели в сваггере, где будут сразу и примеры, и то, что будет возвращаться, допустим, для удобного парсинга?
> 
> 
> Повторю, в публичном апи пока не так много методов, что бы засовывать его в сваггер.
> 
> Насчет выдачи зп.
> Почему бы не запросить у пользователя номер карты, записать в бд и вместо того, что бы досить парсером сайт спворлдс лишними запросами, вытаскивать необходимые данные из своей бд?

1. сваггер даже для 3-7 эндпоинтов полезно, что такого сделать сваггер, особенно при учете того, что он делается легко
2. лишние телодвижения, надо создавать отдельные таблицы, а когда надо делать сразу много транзакций единовременно, это увеличивает скорость отклика(в зависимости от субд конечно)

**Comment by CheppyJam** [comment]
По поводу получения гига чад юзера.
Сразу нет. Такого не будет.

В планах сделать метод для получения только карт пользователя.

В формате 
```
[{'name':'SPWorlds','number':'00001'},....]
```

**Comment by Karonus** [comment]
Получение полного профиля игрока не будет реализовано (в ближайшее время точно).
Однако, скоро появится возможность получить список **активных** карт **любого**. Так же появится возможность получить профиль **владельца** API токена.

Пример ответа на запрос на получение всех **активных** карт игрока:
```json
[
   {
      "name":"Test",
      "number":"01234"
   }
]
```

В сваггере не вижу смысла.
