### ISSUE TITLE
Сделать бы нормальные всплывающие окна...

### ISSUE THREAD

**Issue by yawaflua** [sp-worlds/api-docs#43]
О чем я?
А о том, чтоб каждое уведомление не на весь экран вылезало, а справа снизу(например, в [бутстрапе есть готовые варианты таких сообщений ](https://getbootstrap.su/docs/5.0/components/toasts/?ysclid=losgsgint9577160967)), почему бы их не использовать? Когда на весь экран вылезает уведа это не оч удобно, а обновление страницы можно сделать посредством обновления частей кода, а не всего (в реакте например это используется по умолчанию), как например, это сделано в гитхабе:
Перелистываешь между вкладками: меняется uri, меняется внешка, но страница не перезагружается, благодаря чему можно без ws спокойно обновлять кол-во аров(например) на счету после транзакции, переходить между всеми(прям вообще всеми) вкладками без полноценных обновлений и т.д. 

Да, это займет какое-то время на переделывание, но все же, у вас не настолько маленький штат разрабов, а ваш фронтенд фреймворк(мейби это svelte) должен быть очень схож по синтаксису с условными vue или react

жду в комментах dees`а кста(заранее привет)

**Comment by deesiigneer** [comment]
> жду в комментах dees`а кста(заранее привет)

Ну если ждешь, тогда уж придется пукнуть своим мнением)
А как это связано с открытым API?
Не, я не против улучшения UI, это же хорошо когда становится удобнее)

**Comment by uuuuuno** [comment]
АХАХАХАХАХАХАХХАХАХ
АХАХАХАХАХА
бутстрап....

**Comment by uuuuuno** [comment]
Предлагаю на php переписать
АХАХАХ

**Comment by teleportx** [comment]
Ну да, на php будет быстрее работать. Да и он современнее чем какой-то typescript. Я вообще хз почему сайт сразу не на php или хотя бы на 1С не написан...

**Comment by teleportx** [comment]
> АХАХАХАХАХАХАХХАХАХ АХАХАХАХАХА бутстрап....

hello gays and tuday i describe u how to crate a simpal websait on butstrap c++

**Comment by yawaflua** [comment]
> > жду в комментах dees`а кста(заранее привет)
> 
> Привет, ну если ждешь, тогда уж придется пукнуть своим мнением) А как это связано с открытым API? Не, я не против улучшения UI, это же хорошо когда становится удобнее)

есть еще вариант написать на почту, но такое конечно

**Comment by Karonus** [comment]
Данный репозиторий создан исключительно для обсуждения публичного API.
Идеи улучшению сайта лучше писать на почту help@spworlds.ru.

*А так, возьмем на заметку, спасибо :)*
