### ISSUE TITLE
PHP Lib 

### ISSUE THREAD

**Issue by AnvilM** [sp-worlds/api-docs#44]
PHP Библиотека для API
https://github.com/AnvilM/SPWorlds

**Comment by MaraydZ** [comment]
легенда

**Comment by teleportx** [comment]
гигачад

**Comment by Karonus** [comment]
Библиотека использует старую версию API. Пожалуйста, ознакомьтесь с [новой документацией](https://github.com/sp-worlds/api-docs/wiki)
