### ISSUE TITLE
Данные переводов в Гугл Таблице

### ISSUE THREAD

**Issue by Kolya-gfx** [sp-worlds/api-docs#45]
Можно ли сделать так что бы когда приходит перевод на карту, то он автоматом вносился в гугл таблицу? Если да то как это реализовать через скрипт или формулу? (Если чо я 0 в програмировании, но изучаю чо как на сп атоматизировать, буду использовать для сбора дохода с палаток) Буду рад фидбеку!

**Comment by Kolya-gfx** [comment]
Начал пробовать через скрипт. Блыгодаря GPT понял и нашел в документации URL API. Он робочий? или что нужно добавить https://spworlds.ru/api/public/ - вот здесь. Перешел по ссылке походуи в правду не робочий.

**Comment by deesiigneer** [comment]
> Начал пробовать через скрипт. Блыгодаря GPT понял и нашел в документации URL API. Он робочий? или что нужно добавить https://spworlds.ru/api/public/ - вот здесь. Перешел по ссылке походуи в правду не робочий.

Все рабочее, читай [документацию](https://github.com/sp-worlds/api-docs/blob/main/AUTHORIZATION.md).

**Comment by Kolya-gfx** [comment]
> > Начал пробовать через скрипт. Блыгодаря GPT понял и нашел в документации URL API. Он роботый? или что нужно добавить https://spworlds.ru/api/public/ - вот здесь. Перешел по ссылке походуи на самом деле не робот.
> 
> Все играл, читай [документацию](https://github.com/sp-worlds/api-docs/blob/main/AUTHORIZATION.md) . Статус работы API можно отслеживать [тут же](https://uptime.deesiigneer.ru/status/spworlds)

Спасбо, понял что работает, но теперь проблема с кодом. Вот мой код из Google Apps Script:


// Функция для обработки данных из вебхука и записи в таблицу
function writeToSheet(requestData) {
  // Проверка наличия необходимых свойств в requestData
  if (!requestData || !requestData.sender || !requestData.receiver || !requestData.amount || !requestData.comment) {
    Logger.log('Invalid requestData:', requestData);
    return;
  }

  // Создание объекта TransferInfo из данных вебхука
  var transferInfo = new TransferInfo(
    requestData.sender,
    requestData.receiver,
    requestData.amount,
    requestData.comment
  );

  // Получение реального никнейма пользователя
  var discordID = "мой дискорд айди";  // Пример discordID
  var walletId = "мой айди";  // Пример walletId
  var walletToken = "мой токен";  // Пример walletToken
  var key = new WalletKey(walletId, walletToken);

  User.getUser(key, discordID, function (user) {
    // Проверка наличия user и его имени перед использованием
    if (user && user.getName) {
      // Обновление имени отправителя в объекте TransferInfo
      transferInfo.sender = user.getName();

      // Запись данных в таблицу
      recordTransfer(transferInfo);

      // Инициировать платеж с SPWorlds
      var spWorlds = new SPWorlds(walletId, walletToken);
      var amount = transferInfo.amount;
      var redirectUrl = 'https://example.com/success';  // Ссылка успешной оплаты

      try {
        var paymentUrl = spWorlds.initPayment(amount, redirectUrl, 'https://api.example.com/webhook', 'SomeString');
        
        // Обработка полученного URL после успешного вызова initPayment
        Logger.log('Payment URL:', paymentUrl);

        // Здесь вы можете выполнять другие действия с полученным URL
      } catch (error) {
        // Обработка ошибки при вызове initPayment
        Logger.error(error);
      }
    } else {
      Logger.log('Invalid user:', user);
    }
  });
}

И вот задача как сделать что бы они записывало данный при переводе автоматически. Да и вообще хоть как то записывало

**Comment by deesiigneer** [comment]
> > > Начал пробовать через скрипт. Блыгодаря GPT понял и нашел в документации URL API. Он роботый? или что нужно добавить https://spworlds.ru/api/public/ - вот здесь. Перешел по ссылке походуи на самом деле не робот.
> 
> > 
> 
> > Все играл, читай [документацию](https://github.com/sp-worlds/api-docs/blob/main/AUTHORIZATION.md) . Статус работы API можно отслеживать [тут же](https://uptime.deesiigneer.ru/status/spworlds)
> 
> 
> 
> Спасибо, понял что работает, но теперь проблема с кодом. Вот мой код из Google Apps Script:
> 
> 
> 
> 
> 
> // Функция для обработки данных из вебхука и записи в таблицу
> 
> function writeToSheet(requestData) {
> 
>   // Проверка наличия необходимых свойств в requestData
> 
>   if (!requestData || !requestData.sender || !requestData.receiver || !requestData.amount || !requestData.comment) {
> 
>     Logger.log('Invalid requestData:', requestData);
> 
>     return;
> 
>   }
> 
> 
> 
>   // Создание объекта TransferInfo из данных вебхука
> 
>   var transferInfo = new TransferInfo(
> 
>     requestData.sender,
> 
>     requestData.receiver,
> 
>     requestData.amount,
> 
>     requestData.comment
> 
>   );
> 
> 
> 
>   // Получение реального никнейма пользователя
> 
>   var discordID = "мой дискорд айди";  // Пример discordID
> 
>   var walletId = "мой айди";  // Пример walletId
> 
>   var walletToken = "мой токен";  // Пример walletToken
> 
>   var key = new WalletKey(walletId, walletToken);
> 
> 
> 
>   User.getUser(key, discordID, function (user) {
> 
>     // Проверка наличия user и его имени перед использованием
> 
>     if (user && user.getName) {
> 
>       // Обновление имени отправителя в объекте TransferInfo
> 
>       transferInfo.sender = user.getName();
> 
> 
> 
>       // Запись данных в таблицу
> 
>       recordTransfer(transferInfo);
> 
> 
> 
>       // Инициировать платеж с SPWorlds
> 
>       var spWorlds = new SPWorlds(walletId, walletToken);
> 
>       var amount = transferInfo.amount;
> 
>       var redirectUrl = 'https://example.com/success';  // Ссылка успешной оплаты
> 
> 
> 
>       try {
> 
>         var paymentUrl = spWorlds.initPayment(amount, redirectUrl, 'https://api.example.com/webhook', 'SomeString');
> 
>         
> 
>         // Обработка полученного URL после успешного вызова initPayment
> 
>         Logger.log('Payment URL:', paymentUrl);
> 
> 
> 
>         // Здесь вы можете выполнять другие действия с полученным URL
> 
>       } catch (error) {
> 
>         // Обработка ошибки при вызове initPayment
> 
>         Logger.error(error);
> 
>       }
> 
>     } else {
> 
>       Logger.log('Invalid user:', user);
> 
>     }
> 
>   });
> 
> }
> 
> 
> 
> И вот задача как сделать что бы он записывал данные при переводе автоматически. Да и вообще что бы хоть как то записывало.
> 
> Буду благодарен за помощь!

Вообще, это уже не связано с работой api, по этому могу рекомендовать учиться работать с Google Apps Script. Не думаю, что тут кто-то будет за тебя писать код)

**Comment by Kolya-gfx** [comment]
Понял мне лишь интересно как использовать вебхук, и где его настройки, так как в документации вроде бы про них ничего не сказано

**Comment by deesiigneer** [comment]
> @deesiigneer Понял мне лишь интересно как использовать вебхук, и где его настройки, так как в документации вроде бы про них ничего не сказано

[вся работа с оплатой тут](https://github.com/sp-worlds/api-docs/blob/main/PAYMENTS.md)
