### ISSUE TITLE
Получение информации о карте

### ISSUE THREAD

**Issue by DearFox** [sp-worlds/api-docs#5]
Хотелось бы иметь возможность получать такие данные как: 
- Количество аров
- Название карты
- Номер карты

Это позволило бы например реализовать отображение денег на карте игрока в моде [#SP wallet](https://github.com/feytox/SPwallet)
Возможно стоило-бы для этой функции добавить отдельную галочку, что-бы юзер одобрял возможность получения этой информации через токен.

**Comment by ronanru** [comment]
Спасибо за предложение. Пока никакие нововведения в API не планируются и наша команда сфокусирована на доработке сайта для людей, а не ботов.

**Comment by N3wSk1Y** [comment]
> Спасибо за предложение. Пока никакие нововведения в API не планируются и наша команда сфокусирована на доработке сайта для людей, а не ботов.

Может тогда OpenSource, чтобы другие пилили ?

**Comment by teleport2** [comment]
Сейчас работает фича получения баланса. Её просто нет в документации.

**Comment by ronanru** [comment]
Добавили:
https://github.com/sp-worlds/api-docs/blob/main/CARD.md
