### ISSUE TITLE
Ошибки в документации "Получение аккаунта владельца токена"

### ISSUE THREAD

**Issue by teleportx** [sp-worlds/api-docs#50]
[Страница документации](https://github.com/sp-worlds/api-docs/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D0%B0-%D0%B2%D0%BB%D0%B0%D0%B4%D0%B5%D0%BB%D1%8C%D1%86%D0%B0-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0)

Сказано, что цвет карты - это строка
![image](https://github.com/sp-worlds/api-docs/assets/77507478/90a1827e-88f0-4806-853c-6d0dc29a0ecf)

Сервер возвращает цвет как число.
![image](https://github.com/sp-worlds/api-docs/assets/77507478/3e5c5d9b-8235-4417-97bf-0915a5036a0b)

**Comment by teleportx** [comment]
Также в документации отсутствует поле `minecraftUUID`, которое возвращает сервер

![image](https://github.com/sp-worlds/api-docs/assets/77507478/d6570723-4ff6-4847-b8bf-a46c2a62ae74)

![image](https://github.com/sp-worlds/api-docs/assets/77507478/3296ce36-18e4-4641-a6c3-5c802aec585d)

**Comment by Karonus** [comment]
Исправлено
