### ISSUE TITLE
Общий ресурспак сп, обновление через DynamicPack mod

### ISSUE THREAD

**Issue by AdamCalculator** [sp-worlds/api-docs#58]
Привет, я AdamRG45, @ресурспакер на СП, есть предложение чтобы по endpoint-у допустим
`https://spworlds.ru/api/sp/sp_pack_repo` выдавало ссылку на репозиторий для ресурспака сп (сейчас https://github.com/AdamCalculator/SPPack)

![image](https://github.com/user-attachments/assets/b50e0fe9-0bd5-45da-9e0e-628baa0e2e6d)
![image](https://github.com/user-attachments/assets/d16c30f1-41e7-4c2b-b961-a28445da2843)

Возникла проблема что щас ссылка ведёт на репозиторий Еврозда, а он сложил полномочия, а она уже у всех на компютерах лежит в ресурспаке, захардкожена, я предлагаю чтобы я в мод добавил возможность парсить эту линку

Вот как-то так:

![image](https://github.com/user-attachments/assets/becd3297-ff31-4401-8f19-de135650010e)

и тогда в будущем, когда и мне придёт время сложить полномочия то такой ситации не возникнет

**Comment by Karonus** [comment]
не относится к публичному API
