### ISSUE TITLE
Нововведения

### ISSUE THREAD

**Issue by ValeraShimchuck** [sp-worlds/api-docs#7]
Информация о территории/городе, узнать баланс игрока, узнать данные об игроке(роль, город и прочее), возможность подать в суд через api, а также получить все дела на игрока. Заприватить терру через аpi, запостить кринж через api. Все что можно сделать на сайте, разрешить через api, для того, чтобы можно создать свои spworlds клиенты, допустим интегрированный в мод.

**Comment by teleport2** [comment]
Как на сайте приватить терру? Это доступно только работникам МинЮста. Или это должно быть доступно всем?

**Comment by ronanru** [comment]
Спасибо за предложение. Пока никакие нововведения в API не планируются и наша команда сфокусирована на доработке сайта для людей, а не ботов.

**Comment by ValeraShimchuck** [comment]
Можно не все, но хотябы такие вещи, как узнать баланс карты, с которой логинишься, не помешало бы. И вопрос, причем тут боты? Я говорил про телеграм клиенты, а не про ботов. Допустим я бы хотел сделать полноценный spworlds, только в моде, чтобы можно быстро все сделать сразу в майне, а не лезть на сайт и что-то ковырять. Ладно, по всей видимости прийдеться через костыли все фичи делать, спасибо за ответ.

**Comment by DearFox** [comment]
> Можно не все, но хотябы такие вещи, как узнать баланс карты, с которой логинишься, не помешало бы. И вопрос, причем тут боты? Я говорил про телеграм клиенты, а не про ботов. Допустим я бы хотел сделать полноценный spworlds, только в моде, чтобы можно быстро все сделать сразу в майне, а не лезть на сайт и что-то ковырять. Ладно, по всей видимости прийдеться через костыли все фичи делать, спасибо за ответ.

Ты можешь или свое апи сделать или реализовать разбор html-а прямо в моде, но игроку прийдется логиниться в моде через свой токкен авторизации или типа того, что не очень безопасно.
