### ISSUE TITLE
"Протухание" токена

### ISSUE THREAD

**Issue by deesiigneer** [sp-worlds/api-docs#9]
После определенного времени (не засекал время), при нажатии кнопки "Оплата", выходит вот такая ошибка:
![error](https://i.imgur.com/PvqSF7I.png)
Я предполагаю, что ошибка из-за истечение срока jwt. Было бы круто, вывести нормальное описание ошибки (тогда добавить сколько времени действителен) или добавить в тело запроса [payments](https://github.com/sp-worlds/api-docs/blob/main/PAYMENTS.md) - `expiration`.

**Comment by ronanru** [comment]
Перевел ошибку на понятный русский. Теперь пишет "Ссылка оплаты устарела". Появится на сайте вместе со следующем обновлением

**Comment by deesiigneer** [comment]
> Перевел ошибку на понятный русский. Теперь пишет "Ссылка оплаты устарела". Появится на сайте вместе со следующем обновлением

а сколько ссылка действительна?

**Comment by ronanru** [comment]
5 минут
